#include <arch/board/board.h>

#include <nuttx/board.h>
#include <arch/board/board.h>

#include "chip.h"
#include "stm32l4_gpio.h"
//add by liushuhe 207.09.08
#include "nucleo-l476rg.h"



/* GPIO pins used by the GPIO Subsystem */

//add by liushuhe 2017.10.12
#define BOARD_NGPIOIN     0 /* Amount of GPIO Input pins */
#define BOARD_NGPIOOUT    10 /* Amount of GPIO Output pins */
#define BOARD_NGPIOINT    2 /* Amount of GPIO Input w/ Interruption pins */

//add by liushuhe 2017.10.09
#define HALL_SENSORA        (GPIO_INPUT | GPIO_PULLDOWN | GPIO_PORTA | GPIO_PIN8)
#define HALL_SENSORB        (GPIO_INPUT | GPIO_PULLDOWN | GPIO_PORTC | GPIO_PIN9)
#define LIGHT_315Mhz        (GPIO_INPUT | GPIO_PULLDOWN | GPIO_PORTB | GPIO_PIN15)


//Photoresistor
#define	ZD801S_SENSOR		(GPIO_PORTB | GPIO_PIN5 | GPIO_INPUT | GPIO_PULLDOWN)

#define GPIO_OUT1         	(GPIO_PORTB | GPIO_PIN7 | GPIO_OUTPUT_SET | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz)

#define CPU_RST_NB    		(GPIO_PORTB | GPIO_PIN14 | GPIO_OUTPUT_CLEAR | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz)  
#define NB_PWR_EN_0    		(GPIO_PORTB | GPIO_PIN1  | GPIO_OUTPUT_SET   | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz)  
#define CPU_PWR_LTE         (GPIO_PORTC | GPIO_PIN9  | GPIO_OUTPUT_SET   | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz)

#define CPU_RST_LTE   		(GPIO_PORTB | GPIO_PIN15 | GPIO_OUTPUT_CLEAR | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz)  

#define LTE_PWR_EN_0   		(GPIO_PORTB | GPIO_PIN2 | GPIO_OUTPUT_SET | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz)

#define LTE_AP_READY  		(GPIO_PORTC | GPIO_PIN8 | GPIO_OUTPUT_CLEAR | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz) 

#define LTE_DTR       		(GPIO_PORTC | GPIO_PIN6 | GPIO_OUTPUT_CLEAR | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz)
#define EE_WP         		(GPIO_PORTB | GPIO_PIN11 | GPIO_OUTPUT_CLEAR | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz) 

 
#define CPU_WDI       		(GPIO_PORTB | GPIO_PIN8 | GPIO_OUTPUT_SET | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz) 
#define CPU_WD_EN     		(GPIO_PORTB | GPIO_PIN5 | GPIO_OUTPUT_SET | GPIO_OUTPUT | GPIO_PUSHPULL | GPIO_SPEED_50MHz) 
//add by liushuhe 2017.10.09
#define GPIO_NB_UART_INT        (GPIO_INPUT | GPIO_PULLUP |GPIO_EXTI | GPIO_PORTC | GPIO_PIN11)
#define GPIO_LTE_UART_INT       (GPIO_INPUT | GPIO_PULLUP |GPIO_EXTI | GPIO_PORTC | GPIO_PIN7)
#define GPIO_INT3         		(GPIO_INPUT | GPIO_PULLUP |GPIO_EXTI | GPIO_PORTB | GPIO_PIN14)

//×¢²ágpioÇý¶¯Éè±¸
int stm32l4_gpiodev_initialize(void);




